language: cpp

os:
  - linux
  - osx

env:
  # (default) build using CMake
  - BUILDSYSTEM=cmake
  # (deprecated) build using SCons
  - BUILDSYSTEM=scons

addons:
  apt:
    packages:
      - scons
      - libgtkmm-2.4-dev
      - librsvg2-bin
      - librsvg2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake gettext gtkmm librsvg scons; fi

before_script:
  - export PATH=$PATH:/usr/local/opt/gettext/bin/

script:
  - ./ci/build.sh
