language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libgtkmm-2.4-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtkmm scons; fi

script: scons -j3
