# -*- Python -*-

from glob import glob

Import('env')

# Compatibility with earlier SCons versions:
if not hasattr(env, 'MOFiles'):
    env.MOFiles = env.MO

locales = map(lambda str: str[:-3], glob('*.po'))
for locale in locales:
    subdir = '/%s/LC_MESSAGES' % locale
    mo = env.MOFiles('locale/'+subdir+'/elfelli', locale)
    env.Install(env['destdir']+env['localedir']+subdir, mo)

Default('.')
