# -*- Python -*-

from glob import glob

Import('env')

locales = map(lambda str: str[:-3], glob('*.po'))
for locale in locales:
    env.MO('locale/%s/LC_MESSAGES/elfelli' % locale, locale)
    env.InstallAs('%s/%s/LC_MESSAGES/elfelli.mo' % (env['localedir'], locale),
                  'locale/%s/LC_MESSAGES/elfelli.mo' % locale)
