# -*- Python -*-

Import('env')

data_files = ['elfelli-logo.svg',
              'negative.svg',
              'positive.svg',
              'negative-plate.svg',
              'positive-plate.svg',
              'ui.xml']

env.Install(env['datadir'], data_files)
