# -*- Python -*-

Import('env')

elfelli_sources = ['Application.cpp',
                   'Canvas.cpp',
                   'Simulation.cpp',
                   'SimulationCanvas.cpp',
                   'Main.cpp']

elfelli = env.Program('elfelli', elfelli_sources)

env.Install(env['bindir'], elfelli)
