# -*- Python -*-

Import('env')

elfelli_sources = ['Application.cpp',
                   'Canvas.cpp',
                   'Simulation.cpp',
                   'SimulationCanvas.cpp',
                   'XmlLoader.cpp',
                   'XmlWriter.cpp',
                   'Main.cpp']

elfelli = env.Program('elfelli', elfelli_sources)
Default(elfelli)
env.Install(env['destdir']+env['bindir'], elfelli)
